question_data = [

    {"type": "boolean",
     "difficulty": "easy",
     "category": "Science: Computers",
     "text": "The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.",
     "answer": "False",
     "incorrect_answer": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
     "text": "'HTML' stands for Hypertext Markup Language.",
     "answer": "True", "incorrect_answer": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
     "text": "Linus Torvalds created Linux and Git.", "answer": "True",
     "incorrect_answer": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
     "text": "The Python programming language gets its name from the British comedy group 'Monty Python.'",
     "answer": "True", "incorrect_answer": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
     "text": "Pointers were not used in the original C programming language; they were added later on in C++.",
     "answer": "False", "incorrect_answer": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
     "text": "The Windows ME operating system was released in the year 2000.",
     "answer": "True", "incorrect_answer": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
     "text": "The first IBM PC was released in 1981.", "answer": "True",
     "incorrect_answer": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
     "text": "Ada Lovelace is often considered the first computer programmer.",
     "answer": "True", "incorrect_answer": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
     "text": "The programming language 'Python' is based off a modified version of 'JavaScript'.",
     "answer": "False", "incorrect_answer": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
     "text": "The logo for Snapchat is a Bell.", "answer": "False",
     "incorrect_answer": ["True"]}
]
